### ISSUE TITLE
Create a Good Readme

### ISSUE THREAD

**Issue by ManthanShettigar** [ManthanShettigar/FunWithPython#1]
Drop your comment down here . so that I can assign you to work on this issue

**Comment by kiran-thilak** [comment]
hi, could you assign the task to me?

**Comment by ManthanShettigar** [comment]
@kiran-thilak  assigned you go ahead !

**Comment by kiran-thilak** [comment]
Thanks. I shall get started.

**Comment by kiran-thilak** [comment]
This repository contains games written in python 3. right...

**Comment by ManthanShettigar** [comment]
@kiran-thilak you can add anything related to python scripts , tools , bot , scraper, projects can be contributed .

**Comment by kiran-thilak** [comment]
Could you please take a look at the the [readme file](https://github.com/kiran-thilak/FunWithPython/blob/master/README.md). And let me know the comments.

**Comment by ManthanShettigar** [comment]
it's great , you can create and I will merge it

**Comment by kiran-thilak** [comment]
Ok sure.
